# Generated by Django 3.2.25 on 2024-07-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240709_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_categories',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogcategory'),
            preserve_default=False,
        ),
    ]
