# Generated by Django 3.2.25 on 2024-07-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_blog_categories_post_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_category',
            new_name='blog_categories',
        ),
    ]
