# Generated by Django 3.2.25 on 2024-07-06 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(help_text='Please enter a review between 10 and 500 characters', max_length=500, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
