# Generated by Django 3.2.25 on 2024-07-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.BooleanField(default=True),
        ),
    ]
