# Generated by Django 3.2.25 on 2024-07-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.BooleanField(default=True, verbose_name='In Stock'),
        ),
    ]
